
server:
  port: 8080

spring:
  application:
    name: discohack-backend

  datasource:
    url: jdbc:sqlite:${user.home}/.discohack/discohack.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

discohack:
  yandex:
    client-id: "912b0deaeaed465fa1dd6241aea47d19"
    client-secret: "716949a771bd4f7d8a2a7884321709d6"
    redirect-uri: "http://localhost:8080/api/auth/yandex/callback"
  mount:
    base-path: "${user.home}/CloudMount"

  cache:
    path: "${user.home}/.cache/discohack/files"
    max-size-bytes: 5368709120


logging:
  level:
    com.discohack: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
  file:
    name: "${user.home}/.discohack/discohack.log"